### ISSUE TITLE
LaTeX Error: No counter 'chapter' defined.

### ISSUE THREAD

**Issue by zhi3** [mohuangrui/ucasproposal#4]
When I built it with `./artratex.sh x Thesis.tex`, it raised the error: `!LaTeX Error: No counter 'chapter' defined.`.

I found the `chapter` is defined in the file `Style/artratex.sty`.

Could you please help fix the issue? Thanks.

**Comment by mohuangrui** [comment]
Hi, yes, I have realized that. It was caused by the last update. You just need to change the 'chapter' to 'section' for the following commands in 'artratex.sty':
```
\newtheorem{theorem}{\theoremname}[chapter]

\newtheorem{definition}{\definitionname}[chapter]

\newtheorem{example}{\examplename}[chapter]
```

I forgot to test these commands for ucasproposal after testing them on ucasthesis.

I will do the update tomorrow after I have access to my Windows and Linux computers.

Thanks!

**Comment by zhi3** [comment]
Thanks. It does work. 💯
